#!/usr/bin/env bash
# GentooHA build launcher
# Usage: bash build.sh [--non-interactive] [--platform ...] [--flavor ...]
#        [--x64-formats ...] [--build-uml-kernel true|false]
#        [--start-stage N] [--clean-state true|false]
#        [--artifact-action a|y|n] [--use-binpkg true|false]
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NON_INTERACTIVE=false
CLI_PLATFORM=""
CLI_FLAVOR=""
CLI_X64_ARTIFACT_FORMATS=""
CLI_BUILD_UML_KERNEL=""
CLI_START_STAGE=""
CLI_CLEAN_STATE=""
CLI_ARTIFACT_ACTION=""
CLI_USE_BINPKG=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --non-interactive)
      NON_INTERACTIVE=true
      shift
      ;;
    --platform)
      CLI_PLATFORM="${2:-}"
      shift 2
      ;;
    --flavor)
      CLI_FLAVOR="${2:-}"
      shift 2
      ;;
    --x64-formats|--x64-artifact-formats)
      CLI_X64_ARTIFACT_FORMATS="${2:-}"
      shift 2
      ;;
    --build-uml-kernel)
      CLI_BUILD_UML_KERNEL="${2:-}"
      shift 2
      ;;
    --start-stage)
      CLI_START_STAGE="${2:-}"
      shift 2
      ;;
    --clean-state)
      CLI_CLEAN_STATE="${2:-}"
      shift 2
      ;;
    --artifact-action)
      CLI_ARTIFACT_ACTION="${2:-}"
      shift 2
      ;;
    --use-binpkg)
      CLI_USE_BINPKG="${2:-}"
      shift 2
      ;;
    --help|-h)
      cat <<'EOF'
Usage: bash build.sh [--non-interactive]
                    [--platform x64|pi3|pi4|pizero2|bbb|pbv2]
                    [--flavor live|installer|debug]
                    [--x64-formats vhd|vdi|iso|img[,...]]
                    [--build-uml-kernel true|false]
                    [--start-stage 1-12]
                    [--clean-state true|false]
                    [--artifact-action a|y|n]
                    [--use-binpkg true|false]
EOF
      exit 0
      ;;
    *)
      echo "ERROR: Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

_OS="$(uname -s 2>/dev/null || echo unknown)"
case "$_OS" in
  MINGW*|MSYS*|CYGWIN*) _ENV="windows-bash" ;;
  Linux*)
    if grep -qsi microsoft /proc/version 2>/dev/null; then
      _ENV="wsl"
    else
      _ENV="linux"
    fi
    ;;
  Darwin*|FreeBSD*|OpenBSD*|NetBSD*) _ENV="unsupported-unix" ;;
  *) _ENV="unknown" ;;
esac

echo "[build.sh] Environment: $_ENV ($(uname -sr 2>/dev/null || echo ?))"

# Decision table:
#   windows-bash  (Git Bash / MSYS2 / Cygwin on Windows) -> delegate to WSL2
#   wsl           (already inside WSL2 Linux)             -> run directly on this Linux
#   linux         (native Linux host)                    -> run directly on this Linux
#   anything else -> unsupported
if [[ "$_ENV" == "unsupported-unix" || "$_ENV" == "unknown" ]]; then
  echo "ERROR: Build stages require Linux (native Linux or WSL2)."
  exit 1
fi

VALID_PLATFORMS=(x64 pi3 pi4 pizero2 bbb pbv2)
VALID_FLAVORS=(live installer debug)

# ── Persistent config: load saved defaults ─────────────────────────────────
STATE_ROOT="${STATE_ROOT:-/var/lib/ha-gentoo-hybrid/state}"
BUILD_CONFIG_FILE="${STATE_ROOT}/build_config"
COMPLETED_STAGE_FILE="${STATE_ROOT}/completed_stage"

_saved_platform=""
_saved_flavor=""
_saved_use_binpkg=""
_saved_x64_artifact_format=""
_saved_build_uml_kernel=""

normalize_x64_artifact_formats() {
  local raw="${1:-}"
  local token
  local normalized=()
  local seen=" "

  raw="${raw//,/ }"
  for token in $raw; do
    token="${token,,}"
    case "$token" in
      both)
        for legacy in img vdi; do
          if [[ "$seen" != *" $legacy "* ]]; then
            normalized+=("$legacy")
            seen+="$legacy "
          fi
        done
        ;;
      img|vdi|vhd|iso)
        if [[ "$seen" != *" $token "* ]]; then
          normalized+=("$token")
          seen+="$token "
        fi
        ;;
      *)
        return 1
        ;;
    esac
  done

  if (( ${#normalized[@]} == 0 )); then
    printf 'vhd\n'
  else
    printf '%s\n' "${normalized[*]}"
  fi
}

if [[ -f "$BUILD_CONFIG_FILE" ]]; then
  # shellcheck source=/dev/null
  source "$BUILD_CONFIG_FILE" 2>/dev/null || true
  _saved_platform="${SAVED_PLATFORM:-}"
  _saved_flavor="${SAVED_FLAVOR:-}"
  _saved_use_binpkg="${SAVED_USE_BINPKG:-}"
  _saved_x64_artifact_format="${SAVED_X64_ARTIFACT_FORMAT:-}"
  _saved_build_uml_kernel="${SAVED_BUILD_UML_KERNEL:-}"
fi

# Compute the next-stage default from completed_stage (do this before prompts)
_completed_stage=""
_default_start_stage=1
if [[ -f "$COMPLETED_STAGE_FILE" ]]; then
  _completed_stage="$(cat "$COMPLETED_STAGE_FILE" 2>/dev/null | tr -dc '0-9' || true)"
  if [[ -n "$_completed_stage" ]] && [[ "$_completed_stage" -ge 1 ]] && [[ "$_completed_stage" -lt 12 ]]; then
    _default_start_stage=$(( _completed_stage + 1 ))
  elif [[ "$_completed_stage" == "12" ]]; then
    _default_start_stage=12
  fi
fi

save_build_config() {
  mkdir -p "$STATE_ROOT"
  cat > "$BUILD_CONFIG_FILE" <<EOF
# GentooHA build config – auto-generated by build.sh
SAVED_PLATFORM="${PLATFORM}"
SAVED_FLAVOR="${FLAVOR}"
SAVED_USE_BINPKG="${USE_BINPKG}"
SAVED_X64_ARTIFACT_FORMAT="${X64_ARTIFACT_FORMATS:-${X64_ARTIFACT_FORMAT:-vhd}}"
SAVED_BUILD_UML_KERNEL="${BUILD_UML_KERNEL:-false}"
EOF
}

if $NON_INTERACTIVE; then
  PLATFORM="${CLI_PLATFORM:-${PLATFORM:-${_saved_platform:-x64}}}"
  FLAVOR="${CLI_FLAVOR:-${FLAVOR:-${_saved_flavor:-installer}}}"
  X64_ARTIFACT_FORMATS="${CLI_X64_ARTIFACT_FORMATS:-${X64_ARTIFACT_FORMATS:-${X64_ARTIFACT_FORMAT:-${_saved_x64_artifact_format:-vhd}}}}"
  BUILD_UML_KERNEL="${CLI_BUILD_UML_KERNEL:-${BUILD_UML_KERNEL:-${_saved_build_uml_kernel:-false}}}"
  START_STAGE="${CLI_START_STAGE:-${START_STAGE:-${_default_start_stage}}}"
  CLEAN_STATE="${CLI_CLEAN_STATE:-${CLEAN_STATE:-false}}"
  ARTIFACT_ACTION="${CLI_ARTIFACT_ACTION:-${ARTIFACT_ACTION:-a}}"
  USE_BINPKG="${CLI_USE_BINPKG:-${USE_BINPKG:-${_saved_use_binpkg:-true}}}"
else
  echo "============================================================"
  echo " GentooHA Build Launcher"
  echo "============================================================"
  echo ""
  echo "Platforms:"
  echo "  x64      - Generic PC / VM  (artifact format selectable: vhd / vdi / iso / img)"
  echo "  pi3      - Raspberry Pi 3   (produces .img)"
  echo "  pi4      - Raspberry Pi 4   (produces .img)"
  echo "  pizero2  - Raspberry Pi Zero 2 W  (produces .img)"
  echo "  bbb      - BeagleBone Black  (produces .img)"
  echo "  pbv2     - PocketBeagle v2 with GPU  (produces .img)"
  echo ""
  _plat_default="${_saved_platform:-x64}"
  while true; do
    read -rp "Platform [${_plat_default}]: " PLATFORM
    PLATFORM="${PLATFORM:-${_plat_default}}"
    if [[ " ${VALID_PLATFORMS[*]} " =~ " ${PLATFORM} " ]]; then break; fi
    echo "Invalid platform. Choose from: ${VALID_PLATFORMS[*]}"
  done

  echo ""
  echo "Flavors:"
  echo "  live       - Bootable live system"
  echo "  installer  - Installs to disk on first boot"
  echo "  debug      - Verbose boot diagnostics on console"
  echo ""
  _flav_default="${_saved_flavor:-installer}"
  while true; do
    read -rp "Flavor [${_flav_default}]: " FLAVOR
    FLAVOR="${FLAVOR:-${_flav_default}}"
    if [[ " ${VALID_FLAVORS[*]} " =~ " ${FLAVOR} " ]]; then break; fi
    echo "Invalid flavor. Choose from: ${VALID_FLAVORS[*]}"
  done

  X64_ARTIFACT_FORMATS="${_saved_x64_artifact_format:-vhd}"
  BUILD_UML_KERNEL="${_saved_build_uml_kernel:-false}"
  if [[ "$PLATFORM" == "x64" ]]; then
    echo ""
    echo "x64 artifact formats:"
    echo "  vhd   - Hyper-V / VirtualBox disk image"
    echo "  vdi   - VirtualBox VDI"
    echo "  iso   - bootable ISO"
    echo "  img   - raw disk image"
    echo "  Enter one or more, comma- or space-delimited."
    echo "  Examples: vhd   |   vhd,iso   |   vdi img"
    echo ""
    while true; do
      read -rp "Artifact formats [${X64_ARTIFACT_FORMATS}]: " X64_ARTIFACT_ANS
      X64_ARTIFACT_FORMATS="$(normalize_x64_artifact_formats "${X64_ARTIFACT_ANS:-${X64_ARTIFACT_FORMATS}}")" || {
        echo "Invalid choice. Use one or more of: vhd, vdi, iso, img."
        continue
      }
      break
    done

    echo ""
    read -rp "Build optional User-Mode Linux kernel too? (y/N) [N]: " UML_ANS
    if [[ "${UML_ANS,,}" == "y" ]]; then
      BUILD_UML_KERNEL="true"
    else
      BUILD_UML_KERNEL="false"
    fi
  else
    BUILD_UML_KERNEL="false"
  fi

  echo ""
  while true; do
    read -rp "Start from stage (1-12) [${_default_start_stage}]: " START_STAGE
    START_STAGE="${START_STAGE:-${_default_start_stage}}"
    if [[ "$START_STAGE" =~ ^[0-9]+$ ]] && [[ "$START_STAGE" -ge 1 ]] && [[ "$START_STAGE" -le 12 ]]; then break; fi
    echo "Enter a number from 1 to 12."
  done

  # Only ask about cleaning when starting at stage 1
  CLEAN_STATE="false"
  if [[ "$START_STAGE" -eq 1 ]]; then
    echo ""
    read -rp "Clean prior stage state? (y/N) [N]: " CLEAN_ANS
    [[ "${CLEAN_ANS,,}" == "y" ]] && CLEAN_STATE="true"
  fi

  echo ""
  _binpkg_default="b"
  [[ "${_saved_use_binpkg}" == "false" ]] && _binpkg_default="s"
  echo "Build method:"
  echo "  b  - Binary packages (fast, uses Gentoo binary host)"
  echo "  s  - Compile from source (slow, full control)"
  echo "  Note: individual packages with custom USE flags always fall back to source."
  echo ""
  while true; do
    read -rp "Build method binary/source (b/s) [${_binpkg_default}]: " BINPKG_ANS
    BINPKG_ANS="${BINPKG_ANS:-${_binpkg_default}}"
    case "${BINPKG_ANS,,}" in
      b) USE_BINPKG="true";  break ;;
      s) USE_BINPKG="false"; break ;;
      *) echo "Invalid choice. Use: b (binary) or s (source)." ;;
    esac
  done

  echo ""
  while true; do
    read -rp "Handle existing artifacts? archive/remove/keep (a/y/n) [a]: " ARTIFACT_ACTION
    ARTIFACT_ACTION="${ARTIFACT_ACTION:-a}"
    case "${ARTIFACT_ACTION,,}" in
      a|y|n) break ;;
      *) echo "Invalid choice. Use: a (archive), y (remove), n (keep)." ;;
    esac
  done

  echo ""
  echo "============================================================"
  echo " Build summary"
  echo "   PLATFORM    = $PLATFORM"
  echo "   FLAVOR      = $FLAVOR"
  if [[ "$PLATFORM" == "x64" ]]; then
    echo "   X64_FORMATS = $X64_ARTIFACT_FORMATS"
    echo "   UML_KERNEL  = $BUILD_UML_KERNEL"
  fi
  echo "   START_STAGE = $START_STAGE  (last completed: ${_completed_stage:-none})"
  echo "   CLEAN_STATE = $CLEAN_STATE"
  echo "   ARTIFACTS   = ${ARTIFACT_ACTION,,} (a=archive, y=remove, n=keep)"
  echo "   USE_BINPKG  = $USE_BINPKG"
  echo "============================================================"
  echo ""
  read -rp "Proceed? (Y/n) [Y]: " PROCEED
  [[ "${PROCEED,,}" == "n" ]] && { echo "Aborted."; exit 0; }

  # Persist selections for next run
  save_build_config
fi

ARTIFACT_ACTION="${ARTIFACT_ACTION,,}"
case "$ARTIFACT_ACTION" in
  a|y|n) ;;
  *) ARTIFACT_ACTION="a" ;;
esac

if [[ "$PLATFORM" == "x64" ]]; then
  X64_ARTIFACT_FORMATS="$(normalize_x64_artifact_formats "${X64_ARTIFACT_FORMATS:-${X64_ARTIFACT_FORMAT:-vhd}}")" || X64_ARTIFACT_FORMATS="vhd"
  X64_ARTIFACT_FORMAT="$X64_ARTIFACT_FORMATS"
  case "${BUILD_UML_KERNEL:-false}" in
    true|false) ;;
    *) BUILD_UML_KERNEL="false" ;;
  esac
else
  X64_ARTIFACT_FORMATS="img"
  X64_ARTIFACT_FORMAT="img"
  BUILD_UML_KERNEL="false"
fi

handle_artifacts() {
  local artifacts_dir="$SCRIPT_DIR/artifacts"
  mkdir -p "$artifacts_dir"

  case "$ARTIFACT_ACTION" in
    a)
      if find "$artifacts_dir" -mindepth 1 -maxdepth 1 ! -name archive | read -r; then
        local ts archive_dir
        ts="$(date +%Y%m%d_%H%M%S)"
        archive_dir="$artifacts_dir/archive/$ts"
        mkdir -p "$archive_dir"
        find "$artifacts_dir" -mindepth 1 -maxdepth 1 ! -name archive -exec mv -f {} "$archive_dir" \;
        echo "[build.sh] Archived existing artifacts to: $archive_dir"
      else
        echo "[build.sh] No existing artifacts to archive."
      fi
      ;;
    y)
      if find "$artifacts_dir" -mindepth 1 -maxdepth 1 | read -r; then
        find "$artifacts_dir" -mindepth 1 -maxdepth 1 -exec rm -rf {} \;
        echo "[build.sh] Removed existing artifacts from: $artifacts_dir"
      else
        echo "[build.sh] No existing artifacts to remove."
      fi
      ;;
    n)
      echo "[build.sh] Keeping existing artifacts in: $artifacts_dir"
      ;;
  esac
}

handle_artifacts

# Always write final artifacts into the workspace artifacts directory.
ARTIFACT_DIR="${ARTIFACT_DIR:-$SCRIPT_DIR/artifacts}"
export PLATFORM FLAVOR START_STAGE CLEAN_STATE ARTIFACT_ACTION USE_BINPKG ARTIFACT_DIR X64_ARTIFACT_FORMAT X64_ARTIFACT_FORMATS BUILD_UML_KERNEL

# ── Windows path (Git Bash / MSYS2 / Cygwin) ──────────────────────────────
# build.sh cannot run build stages here; delegate to WSL2.
if [[ "$_ENV" == "windows-bash" ]]; then
  echo "[build.sh] Windows shell detected — delegating to WSL2."
  WSL_DISTRO=""
  # Prefer Debian (apt-based build host) over GentooHA.
  if wsl -d Debian -u root -- echo ok >/dev/null 2>&1; then
    WSL_DISTRO="Debian"
  elif wsl -d GentooHA -u root -- echo ok >/dev/null 2>&1; then
    WSL_DISTRO="GentooHA"
  fi
  if [[ -z "$WSL_DISTRO" ]]; then
    echo "ERROR: No suitable WSL2 distro found (need GentooHA or Debian)."
    echo "Run scripts/windows/prereq_wsl_debian.cmd first."
    exit 1
  fi
  WSL_PATH="$(wsl wslpath "$(pwd -W)" 2>/dev/null || true)"
  if [[ -z "$WSL_PATH" ]]; then
    WSL_PATH="$(echo "$SCRIPT_DIR" | sed 's|^\([A-Za-z]\):|/mnt/\L\1|; s|\\|/|g')"
  fi
  echo "[build.sh] WSL distro: $WSL_DISTRO  path: $WSL_PATH"
  wsl -d "$WSL_DISTRO" -u root -- bash -c \
    "export PLATFORM='$PLATFORM' FLAVOR='$FLAVOR' START_STAGE='$START_STAGE' CLEAN_STATE='$CLEAN_STATE' ARTIFACT_ACTION='$ARTIFACT_ACTION' USE_BINPKG='$USE_BINPKG' X64_ARTIFACT_FORMAT='$X64_ARTIFACT_FORMAT' X64_ARTIFACT_FORMATS='$X64_ARTIFACT_FORMATS' BUILD_UML_KERNEL='$BUILD_UML_KERNEL' END_STAGE='${END_STAGE:-}'; cd '$WSL_PATH' && bash build.sh --non-interactive"
  exit $?
fi

# ── Linux path (native Linux or already inside WSL2) ───────────────────────
# Run build stages directly on this Linux environment.
echo "[build.sh] Linux environment ($_ENV) — running build stages directly."
if [[ "$CLEAN_STATE" == "true" ]]; then
  echo "Cleaning stage state files in $STATE_ROOT ..."
  rm -f "$STATE_ROOT"/stage*.done "$STATE_ROOT"/completed_stage 2>/dev/null || true
fi

echo ""
echo "Starting build: PLATFORM=$PLATFORM FLAVOR=$FLAVOR START_STAGE=$START_STAGE END_STAGE=${END_STAGE:-12}"
bash "$SCRIPT_DIR/scripts/gentoo/run_all.sh"
