--enable CONFIG_OVERLAY_FS
--enable CONFIG_DUMMY
--module CONFIG_MACVLAN
--module CONFIG_IPVLAN
--enable CONFIG_NETFILTER
--enable CONFIG_NETFILTER_ADVANCED
--enable CONFIG_NF_CONNTRACK
--enable CONFIG_NF_NAT
--enable CONFIG_NF_NAT_TFTP
--enable CONFIG_NF_CONNTRACK_TFTP
--enable CONFIG_IP_NF_IPTABLES
--enable CONFIG_IP_NF_FILTER
--enable CONFIG_IP_NF_TARGET_MASQUERADE
--enable CONFIG_IP_NF_TARGET_REJECT
--enable CONFIG_NETFILTER_XT_MATCH_ADDRTYPE
--enable CONFIG_NETFILTER_XT_MATCH_CONNTRACK
--enable CONFIG_NETFILTER_XT_TARGET_MASQUERADE
--enable CONFIG_NF_TABLES
--enable CONFIG_NFT_NAT
--enable CONFIG_NFT_MASQ
--enable CONFIG_BRIDGE
--enable CONFIG_BRIDGE_NETFILTER
--enable CONFIG_VETH
--enable CONFIG_NAMESPACES
--enable CONFIG_NET_NS
--enable CONFIG_PID_NS
--enable CONFIG_IPC_NS
--enable CONFIG_UTS_NS
--enable CONFIG_USER_NS
--enable CONFIG_CGROUPS
--enable CONFIG_CGROUP_FREEZER
--enable CONFIG_CGROUP_DEVICE
--enable CONFIG_CGROUP_CPUACCT
--enable CONFIG_CGROUP_SCHED
--enable CONFIG_CPUSETS
--enable CONFIG_MEMCG
--enable CONFIG_CGROUP_NET_PRIO
--enable CONFIG_CGROUP_HUGETLB
--enable CONFIG_BPF
--enable CONFIG_BPF_SYSCALL
--enable CONFIG_CGROUP_BPF
--enable CONFIG_SECCOMP
--enable CONFIG_SECCOMP_FILTER
--enable CONFIG_POSIX_MQUEUE
--enable CONFIG_KEYS
--module CONFIG_BLK_DEV_LOOP
--module CONFIG_SQUASHFS
--enable CONFIG_SQUASHFS_XATTR
--enable CONFIG_SQUASHFS_XZ
--module CONFIG_ISO9660_FS
--module CONFIG_UDF_FS
--module CONFIG_VIRTIO_PCI
--module CONFIG_VIRTIO_BLK
--module CONFIG_VIRTIO_NET
--module CONFIG_VIRTIO_SCSI
--module CONFIG_HYPERV
--module CONFIG_HYPERV_UTILS
--module CONFIG_HYPERV_NET
--module CONFIG_HYPERV_STORAGE
--module CONFIG_XEN
--module CONFIG_XEN_BLKDEV_FRONTEND
--module CONFIG_XEN_NETDEV_FRONTEND
--module CONFIG_DRM_VBOXVIDEO
--module CONFIG_VBOXSF_FS
--enable CONFIG_SECURITY
--enable CONFIG_SECURITY_NETWORK
--enable CONFIG_SECURITY_PATH
--enable CONFIG_SECURITY_APPARMOR
--enable CONFIG_SECURITY_APPARMOR_BOOTPARAM_VALUE
--set-str CONFIG_LSM "lockdown,yama,apparmor"
--enable CONFIG_AUDIT
--enable CONFIG_AUDITSYSCALL
--enable CONFIG_AUDIT_WATCH
--enable CONFIG_AUDIT_TREE
